Repository stackabletech/stackable-cockpit, pull requests merged in 2024-11, with the labels that each got.

#334 chore: Release stackablectl-24.11.0
  .github/workflows/pr_pre-commit.yml
  .pre-commit-config.yaml
  Cargo.lock
  Cargo.nix
  extra/man/stackablectl.1
  rust/stackablectl/CHANGELOG.md
  rust/stackablectl/Cargo.toml
Labels: release/2024-11

#337 feat: Add shell completions for Nushell and Elvish
  .pre-commit-config.yaml
  Cargo.lock
  Cargo.nix
  Cargo.toml
  docs/modules/stackablectl/partials/commands/completions.adoc
  extra/completions/_stackablectl
  extra/completions/stackablectl.bash
  extra/completions/stackablectl.elv
  extra/completions/stackablectl.fish
  extra/completions/stackablectl.nu
  rust/stackablectl/CHANGELOG.md
  rust/stackablectl/Cargo.toml
  rust/stackablectl/src/cmds/completions.rs
  rust/xtask/Cargo.toml
  rust/xtask/src/completions.rs
  rust/xtask/src/main.rs
Labels: type/feature-new

#336 fix: Sort operator versions by semver version
  .github/workflows/pr_pre-commit.yml
  .pre-commit-config.yaml
  README.md
  crate-hashes.json
  rust/stackablectl/CHANGELOG.md
  rust/stackablectl/src/cmds/operator.rs
  web/build.rs
Labels: type/bug
